DBQuery/Execute(sql_query=src.sql,cursor_handler=default_cursor, log_error = 1)
	Close()
	. = _dm_db_execute(_db_query,sql_query,db_connection._db_con,cursor_handler,null)
	if(!.)
		if(dbcon.Connect())
			_dm_db_execute(_db_query,sql_query,db_connection._db_con,cursor_handler,null)
		else
			to_chat(usr, "<span class='danger'>A SQL error occured during this operation, reconnection has failed.</span>")
		if(log_error)
			log_sql("[ErrorMsg()] | Query used: [sql]")